[phases.setup]
nixPkgs = ["nodejs_20", "yarn", "caddy"]

[phases.install]
cmds = [
  "npm i -g corepack@latest",
  "corepack enable",
  "corepack prepare yarn@4.9.2 --activate",
  "yarn install --immutable --immutable-cache"
]

[phases.build]
cmds = [
  "yarn workspace @poloniex-platform/web run build"
]

[start]
cmd = "caddy run --config apps/web/Caddyfile --adapter caddyfile"
