[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip install uv",
  "uv pip install --system -e ."
]

[start]
cmd = "uvicorn health:app --host 0.0.0.0 --port $PORT"
