[phases.setup]
nixPkgs = ["nodejs_22", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python3.11 -m pip install -r backend/src/ml/requirements.txt"
]

[phases.build]
cmds = ["echo 'Using pre-built dist folder'"]

[start]
cmd = "npm start"
